name: Publish Docker Image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: shell
        run: |
          echo "version=$(git describe --abbrev=0 --tags HEAD | cut -d'v' -f 2)" >> $GITHUB_OUTPUT

      - name: Build and Push (dev)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            lvtianyi3/metatube-sdk-go:dev
            ghcr.io/lvtianyi3/metatube-sdk-go:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push (latest)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            lvtianyi3/metatube-sdk-go:latest
            lvtianyi3/metatube-sdk-go:${{ steps.shell.outputs.version }}
            ghcr.io/lvtianyi3/metatube-sdk-go:latest
            ghcr.io/lvtianyi3/metatube-sdk-go:${{ steps.shell.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
